# Generated by Django 5.1.5 on 2025-02-26 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_age', '0002_remove_customuser_position_alter_customuser_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='hired_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
