# Generated by Django 5.1.5 on 2025-02-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_age', '0003_alter_customuser_hired_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, default='+996', max_length=15),
        ),
    ]
