# Generated by Django 5.1.5 on 2025-02-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='books/', verbose_name='загрузите фото')),
                ('title', models.CharField(max_length=100, verbose_name='укажите названия книги')),
                ('description', models.TextField(blank=True, verbose_name='укажите описания книги')),
                ('price', models.PositiveIntegerField(default=200, verbose_name='укажите цену')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('genre', models.CharField(choices=[('HORROR', 'HORROR'), ('COMEDY', 'COMEDY'), ('FANTASY', 'FANTASY')], default='HORROR', max_length=10, verbose_name='выберите жаныр')),
                ('email', models.EmailField(max_length=100, verbose_name='укажите почту')),
                ('director', models.CharField(default='Иванов Иван', max_length=100)),
                ('audio', models.URLField(verbose_name='укажите ссылку из YOUTUBE')),
            ],
        ),
    ]
