# Generated by Django 5.1.5 on 2025-02-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmodel',
            options={'verbose_name': 'книга', 'verbose_name_plural': 'книги'},
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='music',
            field=models.FileField(blank=True, null=True, upload_to='music/', verbose_name='загрузите музыку'),
        ),
    ]
