# Generated by Django 5.1.5 on 2025-02-15 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='book',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
