# Generated by Django 5.1.5 on 2025-02-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='media_type',
            field=models.CharField(choices=[('mashina.kg', 'mashina.kg'), ('rezka.ag', 'rezka.ag')], default='rezka.ag', max_length=50),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='like',
            field=models.CharField(max_length=50),
        ),
    ]
