# Generated by Django 5.1.5 on 2025-02-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_carmodel_media_type_alter_carmodel_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='RezkaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='media_type',
        ),
    ]
