# Generated by Django 5.1.5 on 2025-02-15 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0005_remove_comment_book_delete_book_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=120)),
                ('choice_status', models.CharField(choices=[('Прочитано', 'Прочитано'), ('Не прочитано', 'Не прочитано')], max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choice_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookmodel')),
            ],
        ),
    ]
